### ISSUE TITLE
Add meta tag description and robots.txt for SEO

### ISSUE THREAD

**Issue by kalvinwang** [cagov/unemployment#137]
Ran a Google Lighthouse audit and it found a couple SEO issues to resolve:

- [ ] Add meta tag description
- [ ] Add robots.txt

**Comment by sharonwarner** [comment]
@mkhandekar do you have any thoughts on what the meta tag description should be?

**Comment by meghscase** [comment]
To clarify, is this for the main page or for all pages. I recommend all.

**Comment by sharonwarner** [comment]
Yes! This will be for all pages.

**Comment by meghscase** [comment]
Cool. On it!

**Comment by kalvinwang** [comment]
To double clarify, it'll be for all pages under /guide/, the six that we control. It won't apply to any other EDD pages.

**Comment by meghscase** [comment]
Hi there,

Here is the proposed meta descriptions for the guide pages. A couple notes:

- I tried to include COVID-19, unemployment assistance, and California in each description.
- Target length was 140-160 characters. 

Main Page: Find out if you’re eligible for unemployment insurance (UI) or pandemic unemployment assistance (PUA) in California and get the information you need to apply due to COVID-19.

What you need before you apply page: Make sure you have the information you need to apply for unemployment insurance (UI) or pandemic unemployment assistance (PUA) in California during COVID-19.

How to apply: Get tips for speeding up the process of your California unemployment insurance (UI) or pandemic unemployment assistance (PUA) application during COVID-19.

After you submit your application: Learn what happens after you apply for California unemployment insurance (UI) and pandemic unemployment assistance (PUA) if you’re self-employed during COVID-19.

Receive your benefits: Learn what happens after you apply for California unemployment insurance (UI) and pandemic unemployment assistance (PUA) if you’re self-employed during COVID-19.

More resources: Get answers to COVID-19 unemployment assistance questions and learn about the types of assistance available to California residents through the CARES Act.

**Comment by meghscase** [comment]
@kalvinwang I just realized I pasted in the same meta description twice and have updated the Receive your benefits one.

**Comment by sharonwarner** [comment]
Closing since we're moving towards deprecating the guide :(
