### ISSUE TITLE
Research | Certification | Plan research 

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#190]
- [x] Research goals and plan
- [x] Moderator guide
- [x] Set up notes doc, synthesis mural and a very lightweight process to quickly integrate changes to the prototype after each usability test

**Comment by mthong** [comment]
Adding some thoughts from a product perspective:

When I think about what do we need to learn from users for the retroactive certification, my main concern is: What are the biggest risks (or unknowns) about the success of the retroactive certification process, that we can de-risk through user research? 

I think the biggest risk is claimant confusion that leads to increased anxiety for claimants, and increased customer support calls for EDD. 

Possible research questions:
* In general, what aspects of the retroactive certification communication and process are most likely to confuse and alarm candidates, resulting in increased calls to EDD? 
* For the publicly-posted website information about retroactively certification, does a user clearly understand what steps to take (and not to take)? 
* If a claimant can't log in to the site because they don't need to retroactively certify, does our message adequately assure them enough that they do not need to take further action? 
* For a claimant who needs to retroactively certify, do they clearly understand why they need to retroactively certify, how to answer the questions, and what will happen next? What do they think will happen as a result of the process?

**Comment by mkhandekar** [comment]
We have completed this research (planned, conducted and synthesized!)
* [CA UI – Retroactive Certification – Moderator Guide](https://docs.google.com/document/d/1FfSrR_QjY4zCzLy67n6HzXGvdM5VBysc0tIX8E492is/edit)
* [CA UI – Retroactive Certification – Observations](https://docs.google.com/document/d/12ii-sZeUlAH-YDxbAbyFX-UvLFpM7D4q1AvBZPtCBzM/edit#heading=h.j0g0o82r7js)
* [CA UI – Retroactive Certification – Recommendations](https://docs.google.com/document/d/1SL0mODEaGaN8qalwRZ8kpvpag8f0660lqZ7CjA9wsC8/edit)
