### ISSUE TITLE
Design | Guide v2 | Add a way for users to switch to Spanish or English

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/unemployment#197]

**Comment by mthong** [comment]
On Friday, 5/18/20, Mai Do from EDD Public Affairs requested this exact feature: 
" It’s our practice to have links with “In English” (on Spanish page) and “En español” (on English) at the top. Can those be added to the English and Spanish pages before we push to production?"

See example on this page: 
https://edd.ca.gov/claims.htm

User story:
As a bilingual reader, I want to be able to switch between the English and Spanish versions of each page of the guide, so that I can read in either language. 

As a Spanish reader, I want to be able to access the Spanish version of the page I'm reading from any page in English, so that I can read in my preferred language. 

Next actions:
- As a team, we need to decide if we can/should add this in as "unplanned work" for the sprint, and what else may need to be deprioritized or scoped down to account for this change. 
- The design team needs to decide where these links would go, and how they will be styled. 

Copying @mkhandekar for visibility.

**Comment by mthong** [comment]
Decisions:
* Add dropdown in grey block

**Comment by nguyen-tina** [comment]
![Screen 2 – Application Requirements](https://user-images.githubusercontent.com/17328158/82340387-29f4d000-99bd-11ea-82ce-1d5f58f32340.png)
This is the mock shared in Slack! 

PROS
- Front and center
- Location implies that language changes will be made for the Guide page only, not the entire EDD experience
- The dropdown interaction allows us to expand to more languages in the future

CONS
- the Language CTA _is_ lower on the page than what might usually be expected, which can cause some confusion
- the words "Select language" is in English, which could be a problem for those who cannot read English. This is a tradeoff we acknowledge, in keeping consistent with Alpha and COVID19.ca.gov pages. Best case scenario, if someone has their browser set to a language, the Guide would automatically load in that language.
