### ISSUE TITLE
USWDS & Bootstrap

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#213]
We used Bootstrap as our design system for the guide, however, design would prefer to use USWDS for the retro-certification application. We need to determine how we can best implement this keeping the following considerations in mind:

- Ideally we'd prefer to have only one design system in the application
- The headers/footers that are used in both the guide and the retro-certification application are written in bootstrap
- Both the guide and the retro-certification application are projects that will probably not exist a year from now
- Other projects that will be build within this application will still exist a year from now (the uploader for example)

**Comment by abquirarte** [comment]
👋 Hi there! We would love to coordinate on this or at least learn from your research. We are also in the process of updating the design standard. Alpha used a modified version of Bootstrap for because it aligned better with the state's current [Web Template](https://beta.template.webstandards.ca.gov/) which we plan to update/enhance as part of Beta. :) 

Here is a bit more on what we have documented so far: https://github.com/cagov/covid19/wiki/Design-Principles-and-style-guide 

Would be great to combine forces!

**Comment by mkhandekar** [comment]
@abquirarte To clarify, is the Alpha team moving towards USWDS, too?
