### ISSUE TITLE
 Detailed confirmation page with answers for each week

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#344]
Post-MVP feature, per [Product Spec for Retroactive Certification](https://docs.google.com/document/d/13dtD1t_xOs2X611Dg3dLysi985dMTtgMWCWLv_hDqkY/edit#heading=h.g30lx3bevur0).

Previously we had [completed time estimates for designing and implemented a detailed confirmation page](https://github.com/cagov/unemployment/issues/255). 

User value: medium
Business value: high - customer support staff can use it 
Level of effort: X

Other notes that might help in scoping this:
* "Alexandra requested timeline estimate for adding more detailed confirmation message, for which there are two cases: (1) logging in for 2nd+ time which is relevant for customer support, (2) after submitting. Let's have a leads conversation about this. We could potentially do design work before launch and then implement after launch."
* "What it means is showing all the answers provided for each week (questions, yes/no answer and income details for #6)."
* There may be a few more lines about this feature in the [timeline document](https://docs.google.com/document/d/1O3qf7hjSuIw5wdU1Pv_A0z5KfgWpzt4VYAHY2dJieNs/edit#).

**Comment by nguyen-tina** [comment]
We reviewed two options for design of this page:
🅰️ Make the weeks on the Confirmation Page into links out to individual Week Certification Pages. When a user clicks on a week, it will take the user to a page that looks like their certification experience. All data is exposed, saved, and unchangeable. They navigate back to the confirmation page or through any other certified week.
Pro: User can access different weeks at a glance
Pro: Familiar experience to actual certification
Con: May bring authorization issues with ISO. Introducing new pages for a signed-in user to view could bring up more issues for ISO

🅱️ Show all Certified Weeks on the Confirmation Page (including all employers). When a user clicks on a week, it expands to display their certification answers. When a user clicks on another week, the current open week would close to keep the page as clean as possible.
Con: Makes for a very very long page, especially on mobile
Con: No easy way to jump to a week in the middle.
Pro: Keep user on one page is very simple hierarchically
Pro: It’s less complex engineering work
Pro: Single-page view has more straightforward authentication
Pro: More simple for the user to simply see their answers

Due to security reasons, we're going to move forward with Option B, and continue exploring in that area.

**Comment by mkhandekar** [comment]
Proposal document with implementation details here: https://docs.google.com/document/d/1Rx1f2J5HPu42e8u8xtH5ggD65Q1-H9ya98D7LiwXSvw/edit
