### ISSUE TITLE
Specific error messages for invalid form data

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#345]
Right now, we require the DOB input fields on the login page to be in a certain range. If a user tries to submit a number outside the specified range, they see a "This field is required." error. We could update that to be more specific. 

There are other validated inputs we could be more specific about as well.

**Comment by sharonwarner** [comment]
Currently, the logic is set up so that the month has to be between 1 and 12, the day has to be between 1 and 31, and the year has to be between 1800 and 2099.

**Comment by mthong** [comment]
I noticed the validation error messages say "This field is required" rather than "This value is out of range" or something similar. Also it looks like the lower bound on the year is 1000, not 1800. 

![image](https://user-images.githubusercontent.com/4636824/85505748-de2cdc00-b5a3-11ea-890e-ac99d3aa9f82.png)

**Comment by sharonwarner** [comment]
Closing since conversion rate is high. Users don't seem to be confused by error messaging.
