### ISSUE TITLE
What baseline data can we use to measure potential reductions in call center worload? 

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#38]
One of our goals is to reduce the need for applicants to phone the call center. 

To measure our impact on this metric over the long term, we need to access to baseline and future data on:
* Volume of UI-related calls answered per time period (E.g. per hour, day, or week)
* Volume of UI-related calls that came in but did not get answered per time period (E.g. per hour, day, or week). I don't know how the call center tracks incoming calls, but if possible it would be could to know how many don't get through or drop before talking to someone. 
* If possible, the top reasons people are calling in for help, with the volume for each types of issue.

**Comment by danachis** [comment]
As you probably saw from the data Eric shared last week, there is baseline data on the number of calls coming in, calls dropped, calls abandoned, calls answered in the ACD system, etc. https://cadotgov.slack.com/archives/C0118STES6P/p1587155169311200 

And now we have some idea why people are contacting EDD from the reasons on the website, even if we don't really have numbers. 

https://docs.google.com/spreadsheets/d/1m2rYIdWd1Q6cB9Uff1XuNPyAeblhzP-P9dIbWFAE9ek/edit#gid=388476798

Great analysis, @mthong! I think you answered your own question. 

The challenge is whether we'll be able to see an effect for having the how-to page. Because EDD is also adding a virtual call center and PAB is constantly updating their copy, how will we know that it was the how-to page that made the needle go up or down?
