### ISSUE TITLE
Accessibility: "Show SSN" placement

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#464]
Social Security number reads bullet for all numbers then option to ‘Show SSN’ is read.  Recommendation to have this information before user enters information.

**Comment by mkhandekar** [comment]
Move "Show SSN" above text field. 

Next steps: 

* Kalvin to research order of reading of aria labels 

If no solid solution available: 

* Tina to do visual explorations for moving "Show SSN" above text field

**Comment by nguyen-tina** [comment]
From Kalvin: 

too bad, the [aria-flowto property](https://a11ysupport.io/tech/aria/aria-flowto_attribute) isn’t supported by any software other than JAWS, so we can’t use it to change the Show SSN reading order 😞

i think we can use aria-describedby so that when entering the SSN field, screen reader users will hear “you can select Show SSN after this input field”, like this example shows: https://ca.non.co.il/index.php/accessible-password-input/

**Comment by nguyen-tina** [comment]
Let's try that route to see if it will be more accessible! I'd like to keep the input field close to the label of the input field as much as possible. If it doesn't pass accessibility, we can then revisit the design.

**Comment by mthong** [comment]
UIB and PAB approve of the text “You can select Show SSN after this input field.” for item 3.

Spanish translation: "Puede seleccionar Mostrar SSN después de este campo de entrada."
