### ISSUE TITLE
Make recommendations to improve participation rate in retroactive certification 

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#610]
- [x] Review social media and identify themes to share with EDD
- [x] Review content of claimant communications and suggest changes to increase urgency 

Background materials: 

1. Here is the current [EDD landing page on retroactive certification](https://edd.ca.gov/Unemployment/retro-certify.htm) 
2. Here are [screenshots of the UIO message](https://docs.google.com/document/d/1WMndWIxysCmov_C3I4VszGtvMf9zmJtOKeusxpILXvs/edit?usp=sharing) sent to claimants (also includes staff-facing screens)
3. The English text message states: "EDD Alert: You must certify for past benefit weeks that were automatically processed. Learn more: [edd.ca.gov/retro.htm](https://edd.ca.gov/Unemployment/retro-certify.htm) Type STOP to opt out, HELP for more info."

**Comment by idealisms** [comment]
Can EDD compare the users that have completed retro certs vs those that haven't? My theory is there is a population of users who haven't done retro certs because they are not currently receiving benefits (either they went back to work or their benefits ran out). Those users probably aren't logging into UIO and might not be seeing the inbox messages. Like, can we (EDD) tell if users that were sent messages in their UIO inbox have logged into UIO to view the message or not?

**Comment by idealisms** [comment]
Oh, haha, I see that's what you have in issue #611!
